[project]
name = "zarr-xarray-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "gcsfs>=2024.12.0",
    "ipykernel>=6.29.5",
    "matplotlib",
    "polars",
    "zarr>=3.0.1",
]
